### ISSUE TITLE
Peer-to-peer code review (2021-11-12)

### ISSUE THREAD

**Issue by piero-vic** [AlexRS90/liderboard#4]
# Peer-to-peer code review
## Things to highlight 
- Good documentation.
## Things to improve
- Remove unused images from repo.
- Try to use just asyn/await instead of then.
https://github.com/AlexRS90/liderboard/blob/7aa5855eb8b10a1f563099b6ba056c6d79128258/src/api.js#L15-L19
- You have a small bug everytime you submit a new score. You may want to try `preventDefault` and add the event listener to the form instead.
https://github.com/AlexRS90/liderboard/blob/7aa5855eb8b10a1f563099b6ba056c6d79128258/src/list.js#L25-L33

**Comment by micheaol** [comment]
# Hi @AlexRS90                                   
Good job so far! Your code looks fine, good job :+1:  :+1: 

## To highlight:
- Gitflow is used :clap:
- Clean code and it's easy to read :clap: 

However, there are some suggestion that you still need to work on, you are almost there!

##  suggestions
- [x] _I would suggest that you make your display score container responsive, so when you have scores it will not push the form away. 
- [ ] Try to use just asyn / await instead :  https://github.com/AlexRS90/liderboard/blob/7aa5855eb8b10a1f563099b6ba056c6d79128258/src/api.js#L21-L34

- [ ] I think you don't need .then if you use async/await:
https://github.com/AlexRS90/liderboard/blob/7aa5855eb8b10a1f563099b6ba056c6d79128258/src/api.js#L15-L19


To state again, Good job Alex.

Cheers and Happy coding!👏👏👏

**Comment by AlexRS90** [comment]
# Hi @micheaol and @piero-vic 
Thanks for your suggestions and for helping me to improve my skills, happy to share with you I already implemented all changes! Take a look in the demo live 😉 

### Cheers! 
### Happy coding 👨‍💻
